### ISSUE TITLE
Code base question

### ISSUE THREAD

**Issue by mconsidine** [jremington/Arduino_heliostat#1]
Hi,
Nicely done project!  In going through the code, if I wanted to adapt it to feeding a fixed (horizontal) telescope, it seems that the "solar concentrator" example would be the easiest to work from.  Is that correct, or is there some nuance I'm missing?  The idea would be to mount the solar scopy due south of a properly aligned alt-az mount.  So the "target" location would be 180 degrees in azimuth and 0 in altitude.  And a loop would run to update the positions.

The "platform_io" example seems to back into the target location by making manual adjustments.

Do I understand the differences correctly?
(I know this isn't technically an issue, but I couldn't figure out how else to get the question to you).
Best regards,
mconsidine

**Comment by jremington** [comment]
The code can point a telescope or solar panel directly at the sun, and automatically track it until the sun is less than 3 degrees altitude.  The code assumes that when azimuth = 0 and altitude = 0, the platform is aligned such that the telescope or solar panel is facing due North, on the horizon.

Simply activate these two commented out lines, and delete the solar concentrator code below them, beginning with the comment "mirror pointing".  Issue the 'a' command (autotrack) to start tracking. Any character on serial input halts the tracking.


```
     // sun tracking
       move_to_altitude(home.getSolarElevation(t_now));
       move_to_azimuth(home.getSolarAzimuth(t_now));
```

**Comment by mconsidine** [comment]
Thanks.  I was actually trying to make sure I understood the configuration for keeping a reflected beam on the same spot over a period of time, with the idea that the coordinates of that spot are known ahead of time.  I think that's what the solar concentrator example shows.Thanks again,Mconsidine On May 31, 2022 8:14 PM, "S. James Remington" ***@***.***> wrote:
The code can point a telescope or solar panel directly at the sun, and automatically track it until the sun is less than 3 degrees from the horizon.  The code assumes that when azimuth = 0 and altitude = 0, the platform is aligned such that the telescope or solar panel is facing due North, along the horizon.
Simply activate these two commented out lines, and delete the solar concentrator code below them, beginning with the comment "mirror pointing".
// sun tracking //      move_to_altitude(home.getSolarElevation(t_now)); //      move_to_azimuth(home.getSolarAzimuth(t_now));

**Comment by jremington** [comment]
The solar concentration code currently **calculates** the alt/az of the target after the target is identified by you, by using serial commands to position the reflected sunlight on the target.

Here is where that calculation is performed:
```
        //get target vector
        Txyz[0] = Nxyz[0] - Sxyz[0];
        Txyz[1] = Nxyz[1] - Sxyz[1];
        Txyz[2] = Nxyz[2] - Sxyz[2];
        Serial.print(F("T: ")); Serial.print(Txyz[0], 3);
        Serial.print(F(" ")); Serial.print(Txyz[1], 3);
        Serial.print(F(" ")); Serial.println(Txyz[2], 3);
        xyz_to_altaz(&talt, &taz, Txyz);
        Serial.print(F("Target alt, az: ")); Serial.print(talt);
        Serial.print(F(" ")); Serial.println(taz);

```

If you know the target alt/az, you can change the code to skip the hand positioning step.
